### ISSUE TITLE
README is out of date

### ISSUE THREAD

**Issue by arsum93** [leroyguillaume/keycloak-bcrypt#15]
I was trying to install this package and I came across some issues with the README.

- The first curl command to get `jbcrypt-0.4` didn't work so I downloaded it from another source, here's what I did `curl https://repo1.maven.org/maven2/org/mindrot/jbcrypt/0.4/jbcrypt-0.4.jar > jbcrypt-0.4.jar`
- I was using Keycloak version 8 so the last curl command in the README was downloading your 1.1.0 release which didn't support version 8 so I updated it to use 1.2.0 with the following `curl -L https://github.com/leroyguillaume/keycloak-bcrypt/releases/download/1.2.0/keycloak-bcrypt-1.2.0.jar > keycloak-bcrypt-1.2.0.jar`

**Comment by leroyguillaume** [comment]
Well, it's fixed! Thank you for this report 😃
