### ISSUE TITLE
Ambiguous configuration, documentation would be useful

### ISSUE THREAD

**Issue by apeschel** [leroyguillaume/keycloak-bcrypt#21]
First off, big thanks for this project, I appreciate your work on this!

This is a fairly minor issue, and could be fixed with just some documentation.

hashedSaltedValue requires a salt of the form "$2y$13$KxiLuFkSlG76vcE8Uc9Fd.EEsXBEQZi7yn/cHDELdiDbiZOhXGfkO", where the hashing algorithm and the work factor are included. But the name is misleading, as the salt+hash is actually just the part after the 3rd $, eg "KxiLuFkSlG76vcE8Uc9Fd.EEsXBEQZi7yn/cHDELdiDbiZOhXGfkO".

hashIterations is confusing to me as well - is the work factor in the hashedSaltedValue used, and hashIterations is ignored? Is hashIterations only used for setting the initial work factor in the hash string? Is the work factor in the hashedSaltedValue string ignored?

**Comment by leroyguillaume** [comment]
Thank you! It's always a pleasure to see somebody happy of this (little) project!

I agree with you but `hashedSaltedValue` and `hashIterations` does not exist anymore in the code since migration to at.favre.lib:bcrypt library. Do you think it would be necessary to add the documentation/rename the variables on this old version?

**Comment by apeschel** [comment]
@leroyguillaume Ah, I didn't realize I was using an old version. It looks like I was using 1.2.0 and the latest release is at 1.5.0.

How is the new key to set for importing existing user hashes? Does the new library work with users created with the old library, or is there a migration required?

**Comment by leroyguillaume** [comment]
Yeah, it moved fast last months!

It is the same key and no migration needed. The new BCrypt library is more recent and the installation is simplified.
