### ISSUE TITLE
Extension can't handle 2b salted hashes

### ISSUE THREAD

**Issue by nomysz** [leroyguillaume/keycloak-bcrypt#22]
I'm currently exporting userbase to Keycloak via it's API and all my hashes in Python are generated with `2b` salts. That means `$2b$12$jsuDs...` like schema. 

I wasn't able to login after uploading such hashes and I tried to research how it works. In the end of the day looks like just simple replace of `2b` -> `2a` on hash export. 

Is it something we can fix in extension implementation? I'm not sure how exactly it works but looks like it's just version of algorythm that generated hash and it shoudn't affect validity of hash.

**Comment by leroyguillaume** [comment]
Hi @nomysz 

What version do you use? 

This problem is an issue from the old BCrypt library (org.mindrot) and I think it's fixed in the new one (at.favre) but I confess I don't check myself.

**Comment by nomysz** [comment]
Hey @leroyguillaume, I'm using `1.5.0` dowloaded from this link https://github.com/leroyguillaume/keycloak-bcrypt/releases/download/1.5.0/keycloak-bcrypt-1.5.0.jar

**Comment by nomysz** [comment]
@leroyguillaume any help/ideas here? 

Here's the `2b`  hash `$2b$12$UF8mQyWXGFOKuRBYBFIsTuu5zOjud0.n2GPgcjMeRDqA8yPzL/36e` generated with this generator https://bcrypthashgenerator.tool-kit.dev/ which I cant make to work with this plugin. Exported user keeps getting `Invalid email or password` message.

**Comment by leroyguillaume** [comment]
This is already the latest release of the library which is used.

The library provides a CLI (https://github.com/patrickfav/bcrypt). Can you use it to test your hash? Maybe you will get more information about how it fails. If not, I can make a new version of this module to display more logs.

**Comment by nielssj** [comment]
Hi @nomysz and @leroyguillaume  

I was able to import our `2b` hashes and successfully login using version `1.5.0` of this extension.

At first I had the exact same issues as @nomysz. It turned out that I had pulled an outdated version of the extension as I somewhat blindly followed this guide: https://dev.to/carnewal/import-existing-users-with-bcrypt-hashed-passwords-in-keycloak-17oo

I import my users using the python client. Here is an example using the hash you posted (which I imported and successfully logged in with):
```python
keycloak_admin = KeycloakAdmin(server_url="http://localhost:8080/auth/",
                               username='admin',
                               password='admin',
                               realm_name='my-app',
                               user_realm_name='master',
                               verify=True)
credentials = [{
    'algorithm': 'bcrypt',
    'hashedSaltedValue': '$2b$12$UF8mQyWXGFOKuRBYBFIsTuu5zOjud0.n2GPgcjMeRDqA8yPzL/36e', # your hash
    'hashIterations': 10,
    'type': 'password'
}]

new_user = keycloak_admin.create_user({
                    "email": 'example@example.com',
                    "username": 'example',
                    "enabled": 'True',
                    "credentials": credentials})
```
