### ISSUE TITLE
Error while running docker-compose command

### ISSUE THREAD

**Issue by anwar-bs** [leroyguillaume/keycloak-bcrypt#24]
The Compose file '.\docker-compose.yml' is invalid because:
services.keycloak.security_opt contains an invalid type, it should be an array

**Comment by leroyguillaume** [comment]
Thank you for your interest @anwar-bs, it is fixed :)

**Comment by anwar-bs** [comment]
> Thank you for your interest @anwar-bs, it is fixed :)

Where can I get the fix ? I am using the latest code and the problem exists

**Comment by leroyguillaume** [comment]
> > Thank you for your interest @anwar-bs, it is fixed :)
> 
> Where can I get the fix ? I am using the latest code and the problem exists

I committed on master branch yesterday
