### ISSUE TITLE
Publish on docker hub

### ISSUE THREAD

**Issue by armujahid** [leroyguillaume/keycloak-bcrypt#26]
I think we should also publish docker image to docker registry :) For now I have published it at https://hub.docker.com/repository/docker/armujahid/keycloak-bcrypt from my repo https://github.com/armujahid/keycloak-bcrypt-container

**Comment by leroyguillaume** [comment]
Thank you for your contribution!

It's a good idea, I'll do that quickly!

**Comment by leroyguillaume** [comment]
It's done!

I wrote new GitHub Actions workflow to build and push new image quickly when a new version of Keycloak is available.
