### ISSUE TITLE
[Discussion] Keycloak 17.0.0 support?

### ISSUE THREAD

**Issue by armujahid** [leroyguillaume/keycloak-bcrypt#27]
Keycloak 17.0.0 has been released with breaking changes. They switched from WildFly to Quarkus. 
https://www.keycloak.org/2022/02/keycloak-1700-released.html
I hope that this provider is still compatible. 
Otherwise we will have to migrate it as mentioned in their migration guide.
https://www.keycloak.org/migration/migrating-to-quarkus
![image](https://user-images.githubusercontent.com/3725386/155661482-105076ba-3bb8-4987-a83f-f134c900dab8.png)

**Comment by leroyguillaume** [comment]
I hope so! But for the moment the Docker image of this version does not exist and I can't test easily without it... The project still compiles with new dependencies, it's a good start. I keep you in touch when the image will be pushed.

**Comment by armujahid** [comment]
Latest docker image is available ar https://quay.io/repository/keycloak/keycloak?tab=tags

They didn't publish it on docker hub.
I will also try to test this with latest version and will let you know.

**Comment by leroyguillaume** [comment]
It's done! The Docker image is available and the README is up-to-date. The code was already compatible, so no change was needed.
