### ISSUE TITLE
Need another panel of keyclcok

### ISSUE THREAD

**Issue by amiranbari** [leroyguillaume/keycloak-bcrypt#30]
Hi, if we need keyclock based on "jboss/keycloak" image.
is there any way to do that ? 
Thanks.

**Comment by leroyguillaume** [comment]
Hello, 
[Here](https://github.com/leroyguillaume/keycloak-bcrypt/blob/d603f86d45a4d45c600c6e837ad00b1f91c18d1d/docker/Dockerfile) an old version of the Dockerfile that uses jboss/keycloak (but it's deprecated, I don't encourage you to use it).

**Comment by amiranbari** [comment]
Thanks 👌
