### ISSUE TITLE
target folder?

### ISSUE THREAD

**Issue by Jono20201** [leroyguillaume/keycloak-bcrypt#5]
Sorry if this is an obvious question, new to wildfly/keycloak -- I have ran the module add command, but I do not have any target folder on my file system. Where is this meant to come from?

**Comment by Jono20201** [comment]
Realised I was being silly. jbcrypt is the support library... got to build from scratch. Not a java developer!

**Comment by leroyguillaume** [comment]
Hahaha 😂
It's a good training however!
