### ISSUE TITLE
default iteration config not same as in origin BCrypt library

### ISSUE THREAD

**Issue by pavelkokush** [leroyguillaume/keycloak-bcrypt#7]
Why default iteration configuration in keycloak-bcrypt  is not same as default iteration configuration in org.mindrot.jbcrypt.BCrypt?
 It is **10** in org.mindrot.jbcrypt.BCrypt 
 It is 8192 in keycloak-bcrypt  which is converted to **14** for org.mindrot.jbcrypt.BCrypt

**Comment by leroyguillaume** [comment]
Hello,

It was a mistake. Thank you for the report!
